logging:
  level:
    reactivefeign:
      client:
        log: trace


management:
  endpoints.web.exposure.include: '*' # health,info,prometheus

  tracing:
    enabled: true
    sampling.probability: 1.0
    propagation:
      type: b3_multi